version: '3'
services:
  db:
    build:
      context: .
      dockerfile: mongo.dockerfile
    expose:
      - "27017"
    ports:
      - "27017:27017" #only for dev
    networks:
      - app-network

  consumer-service:
    restart: always
    build:
      context: ./backend/consumer-service
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080"
    depends_on:
      - db
    networks:
      - app-network

  producer-service:
    restart: always
    build:
      context: ./backend/producer-service
      dockerfile: Dockerfile
    expose:
      - "8081"
    ports:
      - "8081"
    depends_on:
      - db
      - consumer-service
    volumes:
      - /home/daniele/ntw-com-proto:/home/daniele/ntw-com-proto:rw
    networks:
      - app-network

  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx.dockerfile
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - consumer-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
