producer:
  polling:
    folder:
      /home/daniele/ntw-com-proto/
  fragments:
    url: api/consumer/fragment
    port: 8080

producerRoutingTable:
  - name: ntw-com-proto_producer-service_1
    master: true
  - name: ntw-com-proto_producer-service_2
    master: false

consumerRoutingTable:
  - name: ntw-com-proto_consumer-service_1
    master: true
  - name: ntw-com-proto_consumer-service_2
    master: true